---
- name: Get Thrift server
  set_fact: metastore_item=thrift://{{ hostvars[item]['ansible_fqdn'] if 'ansible_fqdn' in hostvars[item] else item }}:9083
  with_items:
    - "{{ groups['mapr-hive-metastore'] }}"
  register: metastore_hosts
- name: Make Hive MetaStore String
  set_fact: metastore_string={{ metastore_hosts.results | map(attribute='ansible_facts.metastore_item') | list | join(',')}}
- name: Get Timeline Server
  set_fact: timelineserver_item={{ hostvars[item]['ansible_fqdn'] if 'ansible_fqdn' in hostvars[item] else item }}
  with_items:
  - "{{ groups['mapr-timelineserver'] }}"
  register: timelineserver_hosts
- name: Make Timeline Server String
  set_fact: timelineserver_string={{ timelineserver_hosts.results | map(attribute='ansible_facts.timelineserver_item') | list | join(',')}}
  when: timelineserver_hosts.results|length > 0
